spring:
#  profiles:
  application:
    name: app-service
  datasource:
    name: green
    url: jdbc:mysql://localhost:3306/green
    username: root
    password: 123456
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
  redis:
    host: 10.122.131.220
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
#druid:
#  url: jdbc:mysql://localhost:3306/green
#  driver-class: com.mysql.jdbc.Driver
#  username: root
#  password: 123456
#  initial-size: 1
#  min-idle: 1
#  max-active: 20
#  test-on-borrow: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

server:
  port: 8080

endpoints:
  shutdown:
    enabled: true